lap_performance_at = [
    "processor speed",
    "boot time",
    "multitasking capability",
    "graphics performance",
    "battery life",
    "heat management",
    "fan noise",
    "system stability",
    "software compatibility",
    "WiFi performance",
    "Bluetooth connectivity",
    "lagging issues",
    "RAM efficiency",
    "storage speed",
    "video playback quality",
    "audio output quality",
    "gaming performance",
    "touchpad responsiveness",
    "keyboard responsiveness",
    "fingerprint scanner efficiency",
    "USB transfer speed",
    "screen refresh rate",
    "application loading time"
]

lap_battery_life_at = [
    "battery capacity",
    "battery longevity",
    "charging speed",
    "battery replacement",
    "battery efficiency",
    "battery performance",
    "battery drain",
    "battery life under load",
    "standby time",
    "battery degradation",
    "power consumption",
    "usage time",
    "battery type",
    "fast charging support",
    "battery health",
    "energy saving features",
    "real-world battery life",
    "battery warranty",
    "battery cycles",
    "maximum battery life"
]

lap_design_at = [
    "color scheme",
    "build quality",
    "keyboard layout",
    "screen bezel size",
    "weight",
    "dimensions",
    "port placement",
    "hinge durability",
    "backlighting",
    "material quality",
    "aesthetic appeal",
    "fingerprint resistance",
    "cooling system design",
    "speaker placement",
    "camera placement",
    "trackpad size",
    "overall ergonomics",
    "screen-to-body ratio",
    "keyboard travel",
    "LED indicators",
    "logo design",
    "chassis rigidity",
    "corner sharpness",
    "ventilation design",
    "touchscreen implementation"
]

lap_display_at =  [
    "screen size",
    "screen resolution",
    "refresh rate",
    "color accuracy",
    "brightness level",
    "contrast ratio",
    "viewing angles",
    "touchscreen functionality",
    "display technology",
    "anti-glare coating",
    "pixel density",
    "HDR support",
    "aspect ratio",
    "color gamut coverage",
    "sRGB coverage",
    "Adobe RGB coverage",
    "screen flicker",
    "bezel size",
    "edge-to-edge display",
    "glossy or matte finish"
]

lap_build_quality_at = [
    "chassis material",
    "keyboard flex",
    "display hinge",
    "surface finish",
    "frame sturdiness",
    "overall durability",
    "quality of plastics",
    "metal body",
    "carbon fiber construction",
    "plastic casing",
    "aluminum frame",
    "build precision",
    "scratch resistance",
    "paint quality",
    "rubber foot stability",
    "speaker grill durability",
    "heat dissipation design",
    "port reinforcement",
    "screw tightness",
    "lid rigidity",
    "water resistance",
    "environmental sealing",
    "keyboard durability",
    "trackpad quality",
    "flex resistance"
]


lap_portability_at = [
    "weight",
    "size dimensions",
    "battery life",
    "compact design",
    "carry case",
    "overall portability",
    "travel-friendly",
    "charging options",
    "wireless capabilities",
    "durability",
    "ease of transport",
    "thickness",
    "lightweight",
    "battery capacity",
    "USB ports number",
    "power adapter size",
    "ergonomics for travel",
    "build quality for mobility",
    "power consumption",
    "sleeve compatibility"
]

lap_price_at = [
    "affordability",
    "value for money",
    "cost",
    "price point",
    "MSRP",
    "discount offers",
    "sale price",
    "financing options",
    "price range",
    "budget-friendly",
    "premium pricing",
    "hidden costs",
    "total cost of ownership",
    "price comparison",
    "initial price",
    "upgrade cost",
    "warranty cost",
    "subscription fees",
    "economic value",
    "investment value"
]

lap_connectivity_at = [
    "Wi-Fi performance",
    "Bluetooth connectivity",
    "USB port compatibility",
    "Ethernet port speed",
    "HDMI output quality",
    "Thunderbolt port availability",
    "SD card reader functionality",
    "NFC capabilities",
    "wireless connection stability",
    "4G/5G cellular connectivity",
    "AirPlay support",
    "Miracast support",
    "Wi-Fi 6 support",
    "USB-C charging speed",
    "Docking station compatibility",
    "DisplayPort performance",
    "VGA output",
    "Audio jack quality",
    "Wi-Fi range",
    "Infrared connectivity options",
    "Wireless charging support"
]

lap_software_at = [
    "operating system",
    "pre-installed software",
    "antivirus software",
    "office suite",
    "graphics software",
    "audio software",
    "video editing software",
    "gaming performance",
    "software compatibility",
    "drivers and utilities",
    "bloatware",
    "software updates",
    "backup software",
    "encryption software",
    "virtualization support",
    "development tools",
    "media playback software",
    "email client",
    "web browsing experience",
    "cloud storage integration"
]
    
lap_warranty_and_support_at = [
    "warranty period",
    "international warranty",
    "warranty service",
    "extended warranty",
    "customer support",
    "technical support",
    "support hotline",
    "online support",
    "replacement policy",
    "return policy",
    "refund policy",
    "repair services",
    "onsite support",
    "remote assistance",
    "service centers",
    "parts warranty",
    "software updates support",
    "troubleshooting guidance",
    "live chat support",
    "email support"
]

res_food_at = [
    "taste",
    "flavor",
    "presentation",
    "portion size",
    "freshness",
    "menu variety",
    "ingredient quality",
    "spice level",
    "texture",
    "temperature",
    "seasoning",
    "authenticity",
    "culinary innovation",
    "dish name",
    "cuisine type",
    "vegetarian options",
    "vegan options",
    "gluten-free options",
    "sauce",
    "meat quality",
    "seafood quality",
    "dessert options",
    "salad freshness",
    "appetizer selection",
    "beverage options",
    "wine list",
    "healthy options",
    "comfort food",
    "food allergy accommodations",
    "chef's specials",
    "side dishes",
    "breakfast options",
    "lunch specials",
    "dinner courses",
    "snack variety",
    "baked goods quality",
    "soup selection",
    "food presentation creativity",
    "food innovation",
    "thematic dishes",
    "food pairing suggestions",
    "special diet accommodations"
]

res_service_at = [
    "wait time",
    "server attentiveness",
    "menu knowledge",
    "reservation handling",
    "friendly staff",
    "table readiness",
    "order accuracy",
    "speed of service",
    "handling of special requests",
    "customer service",
    "wine recommendation",
    "water refill efficiency",
    "bill processing time",
    "staff professionalism",
    "server manner",
    "order adjustment handling",
    "communication skills",
    "greeting at the door",
    "farewell on leaving",
    "handling complaints",
    "staff uniform cleanliness",
    "manager availability",
    "server availability",
    "table clearing speed",
    "respectfulness of staff"
]

res_ambiance_at = [
    "lighting",
    "music",
    "decor",
    "atmosphere",
    "noise level",
    "seating comfort",
    "table spacing",
    "cleanliness",
    "temperature",
    "vibe",
    "theme",
    "acoustic",
    "outdoor seating",
    "view",
    "crowdedness",
    "privacy",
    "scent",
    "color scheme",
    "artwork",
    "cultural decorations"
]

res_price_at = [
    "menu prices",
    "value for money",
    "drink prices",
    "dinner prices",
    "lunch specials prices",
    "happy hour deals",
    "buffet pricing",
    "meal deals",
    "set menu price",
    "appetizer prices",
    "dessert prices",
    "wine list prices",
    "specials pricing",
    "food quality for the price",
    "portion size to price ratio",
    "tip expectations",
    "service charge",
    "hidden costs",
    "group pricing",
    "family meal deals",
    "takeout pricing",
    "delivery fees",
    "seasonal menu pricing",
    "price range",
    "discounts and offers",
]

res_cleanliness_at = [
    "bathroom cleanliness",
    "kitchen hygiene",
    "table cleanliness",
    "floor cleanliness",
    "cutlery cleanliness",
    "glassware cleanliness",
    "plate cleanliness",
    "staff hygiene",
    "sanitization measures",
    "food preparation cleanliness",
    "dishwashing standards",
    "overall cleanliness",
    "cleaning practices",
    "trash disposal",
    "pest control",
    "air quality",
    "handwashing facilities",
    "surface disinfection",
    "server cleanliness",
    "cleanliness of condiment holders"
]

res_location_at = [
    "central location",
    "easy access",
    "parking availability",
    "scenic view",
    "public transit access",
    "neighborhood",
    "proximity to attractions",
    "traffic congestion",
    "walking distance",
    "waterfront location",
    "city center",
    "quiet area",
    "street noise",
    "ambiance around",
    "safety of the area",
    "outdoor seating location",
    "patio view",
    "entrance accessibility",
    "historical district",
    "landmark nearby",
    "secluded spot",
    "riverside location",
    "rooftop view",
    "garden setting",
    "proximity to hotels"
]

res_reservations_at = [
    "booking process",
    "reservation system",
    "waiting list",
    "table availability",
    "online booking ease",
    "reservation flexibility",
    "booking confirmation",
    "cancellation policy",
    "group bookings",
    "advance booking requirement",
    "reservation accuracy",
    "phone reservation service",
    "booking fee",
    "peak time availability",
    "last-minute booking",
    "booking platform interface",
    "reservation assistance",
    "special request handling",
    "reservation timing",
    "member reservation privileges"
]

lap_at = {
    "performance" : lap_performance_at,
    "battery life" : lap_battery_life_at,
    "design" : lap_design_at,
    "display" : lap_display_at,
    "build quality" : lap_build_quality_at,
    "portability" : lap_portability_at,
    "price" : lap_price_at,
    "connectivity" : lap_connectivity_at,
    "software" : lap_software_at,
    "warranty and support" : lap_warranty_and_support_at
}

res_at = {
    "food" : res_food_at,
    "service" : res_service_at,
    "ambiance" : res_ambiance_at,
    "price" : res_price_at,
    "cleanliness" : res_cleanliness_at,
    "location" : res_location_at,
    "reservations" : res_reservations_at
}
    