res_opinions =  {
    "food": [
        ["delicious", "positive"],
        ["tasty", "positive"],
        ["flavorful", "positive"],
        ["savory", "positive"],
        ["mouth-watering", "positive"],
        ["exquisite", "positive"],
        ["succulent", "positive"],
        ["delectable", "positive"],
        ["appetizing", "positive"],
        ["yummy", "positive"],
        ["juicy", "positive"],
        ["rich", "positive"],
        ["heavenly", "positive"],
        ["perfectly cooked", "positive"],
        ["fresh", "positive"],
        ["homemade", "positive"],
        ["creamy", "positive"],
        ["crispy", "positive"],
        ["tender", "positive"],
        ["spicy", "positive"],
        ["innovative", "positive"],
        ["well-seasoned", "positive"],
        
        ["bland", "negative"],
        ["flavorless", "negative"],
        ["tasteless", "negative"],
        ["overcooked", "negative"],
        ["undercooked", "negative"],
        ["dry", "negative"],
        ["stale", "negative"],
        ["greasy", "negative"],
        ["soggy", "negative"],
        ["burnt", "negative"],
        ["salty", "negative"],
        ["too sweet", "negative"],
        ["acidic", "negative"],
        ["bitter", "negative"],
        ["spicy", "negative"],  # can be positive or negative depending on context
        ["boring", "negative"],
        ["unappealing", "negative"],
        ["heavy", "negative"],
        ["artificial", "negative"],
        ["cold", "negative"],
        
        ["mediocre", "neutral"],
        ["average", "neutral"],
        ["okay", "neutral"],
        ["standard", "neutral"],
        ["common", "neutral"],
        ["ordinary", "neutral"],
        ["typical", "neutral"],
        ["acceptable", "neutral"],
        ["satisfactory", "neutral"],
        ["fine", "neutral"]
    ],
    "service": [
        ["attentive", "positive"],
        ["friendly", "positive"],
        ["efficient", "positive"],
        ["professional", "positive"],
        ["prompt", "positive"],
        ["courteous", "positive"],
        ["welcoming", "positive"],
        ["knowledgeable", "positive"],
        ["helpful", "positive"],
        ["personalized", "positive"],
        ["accommodating", "positive"],
        ["slow", "negative"],
        ["rude", "negative"],
        ["neglectful", "negative"],
        ["unprofessional", "negative"],
        ["dismissive", "negative"],
        ["inattentive", "negative"],
        ["impolite", "negative"],
        ["overwhelmed", "negative"],
        ["unfriendly", "negative"],
        ["inexperienced", "negative"],
        ["unhelpful", "negative"],
        ["unaccommodating", "negative"],
        ["average", "neutral"],
        ["standard", "neutral"],
        ["acceptable", "neutral"],
        ["basic", "neutral"],
        ["routine", "neutral"]
    ],
    "ambiance": [
        ["cozy", "positive"],
        ["charming", "positive"],
        ["inviting", "positive"],
        ["romantic", "positive"],
        ["vibrant", "positive"],
        ["lively", "positive"],
        ["unique", "positive"],
        ["elegant", "positive"],
        ["stylish", "positive"],
        ["sophisticated", "positive"],
        ["trendy", "positive"],
        ["quaint", "positive"],
        ["relaxing", "positive"],
        ["peaceful", "positive"],
        ["serene", "positive"],
        ["bright", "positive"],
        ["airy", "positive"],
        ["warm", "positive"],
        ["welcoming", "positive"],
        
        ["crowded", "negative"],
        ["noisy", "negative"],
        ["cramped", "negative"],
        ["claustrophobic", "negative"],
        ["stuffy", "negative"],
        ["dull", "negative"],
        ["drab", "negative"],
        ["outdated", "negative"],
        ["tacky", "negative"],
        ["loud", "negative"],
        ["dark", "negative"],
        ["dingy", "negative"],
        ["smoky", "negative"],
        ["smelly", "negative"],
        ["grimy", "negative"],
        ["uncomfortable", "negative"],
        ["generic", "negative"],
        ["soulless", "negative"],
        ["bland", "nehative"],
        
        ["casual", "neutral"],
        ["simple", "neutral"],
        ["functional", "neutral"],
        ["standard", "neutral"],
        ["traditional", "neutral"],
        ["familiar", "neutral"],
        ["ordinary", "neutral"],
        ["modest", "neutral"]
    ],
    "price": [
        ["affordable", "positive"],
        ["cheap", "positive"],
        ["cost-effective", "positive"],
        ["great value", "positive"],
        ["great value for the money", "positive"],  # Considering 'great value' and 'great value for the money' have slightly different nuances
        ["reasonably priced", "positive"],
        ["good value", "positive"],
        ["worth every penny", "positive"],
        ["inexpensive", "positive"],
        ["budget-friendly", "positive"],
        ["economical", "positive"],
        ["priced fairly", "positive"],
        ["overpriced", "negative"],
        ["expensive", "negative"],
        ["pricey", "negative"],
        ["rip-off", "negative"],
        ["costly", "negative"],
        ["high-end", "negative"],
        ["steep", "negative"],
        ["exorbitant", "negative"],  
        ["fairly priced", "neutral"],
        ["moderate", "neutral"],
        ["mid-range", "neutral"],
        ["average priced", "neutral"],
        ["standard pricing", "neutral"],
        ["not worth the money", "negative"],
        ["a bit much", "negative"],
        ["on the higher side", "neutral"]
    ],
    "location": [
        ["centrally located", "positive"],
        ["easy to find", "positive"],
        ["convenient location", "positive"],
        ["perfectly situated", "positive"],
        ["ideal location", "positive"],
        ["conveniently located", "positive"],
        ["great view", "positive"],
        ["accessible", "positive"],
        ["hidden gem", "positive"],
        
        ["inconvenient location", "negative"],
        ["far-flung", "negative"],
        ["poorly located", "negative"],
        ["noisy area", "negative"],
        ["crowded area", "negative"],
        ["bad neighborhood", "negative"],
        ["lacks parking", "negative"],
        ["difficult to access", "negative"],
        ["far from public transport", "negative"],
        
        ["downtown", "neutral"],
        ["near the waterfront", "neutral"],
        ["suburban", "neutral"],
        ["in a shopping district", "neutral"],
        ["nearby parking", "neutral"],
        ["adjacent to", "neutral"]
    ],
    "cleanliness": [
        ["spotless", "positive"],
        ["immaculate", "positive"],
        ["clean", "positive"],
        ["well-maintained", "positive"],
        ["pristine", "positive"],
        ["hygienic", "positive"],
        ["sanitary", "positive"],
        ["tidy", "positive"],
        
        ["dirty", "negative"],
        ["filthy", "negative"],
        ["unclean", "negative"],
        ["grubby", "negative"],
        ["messy", "negative"],
        ["neglected", "negative"],
        ["unsanitary", "negative"],
        ["grimy", "negative"],
        ["gross", "negative"],
        ["unhygienic", "negative"],
        
        ["acceptable", "neutral"],
        ["adequate", "neutral"],
        ["average", "neutral"],
        ["fair", "neutral"],
        ["okay", "neutral"],
        ["passable", "neutral"]
    ],
    "reservations":[
        ["easy-to-make", "positive"],
        ["seamless", "positive"],
        ["hassle-free", "positive"],
        ["prompt", "positive"],
        ["efficient", "positive"],
        ["convenient", "positive"],
        ["user-friendly", "positive"],
        ["quick", "positive"],
        ["straightforward", "positive"],
        ["flexible", "positive"],

        ["difficult", "negative"],
        ["complicated", "negative"],
        ["time-consuming", "negative"],
        ["frustrating", "negative"],
        ["inconvenient", "negative"],
        ["problematic", "negative"],
        ["slow", "negative"],
        ["unresponsive", "negative"],
        ["rigid", "negative"],
        ["cumbersome", "negative"],

        ["standard", "neutral"],
        ["usual", "neutral"],
        ["expected", "neutral"],
        ["typical", "neutral"],
        ["average", "neutral"],
        ["normal", "neutral"],
        ["regular", "neutral"],
        ["common", "neutral"],
        ["basic", "neutral"],
        ["standardized", "neutral"]
    ]
}

laptop_aspect_categories_filtered = [
    "performance",
    "design",
    "display",
    "battery life",
    "portability",
    "price",
    "build quality",
    "connectivity",
    "software",
    "warranty and support",
]

lap_opinions = {
    "performance" :[
        ["lightning-fast", "positive"],
        ["high-speed", "positive"],
        ["powerful", "positive"],
        ["efficient", "positive"],
        ["smooth", "positive"],
        ["impressive", "positive"],
        ["responsive", "positive"],
        ["superb", "positive"],
        ["lag-free", "positive"],
        ["optimal", "positive"],
        ["unrivaled", "positive"],
        ["peak performance", "positive"],
        ["blazing fast", "positive"],
        ["top-notch", "positive"],

        ["adequate", "neutral"],
        ["sufficient", "neutral"],
        ["acceptable", "neutral"],
        ["moderate", "neutral"],
        ["average", "neutral"],
        ["decent", "neutral"],
        ["standard", "neutral"],

        ["slow", "negative"],
        ["laggy", "negative"],
        ["unresponsive", "negative"],
        ["underpowered", "negative"],
        ["poor", "negative"],
        ["disappointing", "negative"],
        ["subpar", "negative"],
        ["lacking", "negative"],
        ["inefficient", "negative"],
        ["sluggish", "negative"],
        ["limited", "negative"],
        ["weak", "negative"],
        ["tedious", "negative"],
        ["problematic", "negative"]
    ],
    "design":  [
        ["sleek", "positive"],
        ["innovative", "positive"],
        ["stylish", "positive"],
        ["cutting-edge", "positive"],
        ["compact", "positive"],
        ["lightweight", "positive"],
        ["portable", "positive"],
        ["elegant", "positive"],
        ["user-friendly", "positive"],
        ["futuristic", "positive"],
        ["durable", "positive"],
        ["clunky", "negative"],
        ["bulky", "negative"],
        ["outdated", "negative"],
        ["heavy", "negative"],
        ["awkward", "negative"],
        ["fragile", "negative"],
        ["unattractive", "negative"],
        ["plain", "negative"],
        ["cheap-looking", "negative"],
        ["impractical", "negative"],
        ["inconvenient", "negative"],
        ["standard", "neutral"],
        ["traditional", "neutral"],
        ["functional", "neutral"],
        ["simple", "neutral"],
        ["minimalistic", "neutral"],
        ["utilitarian", "neutral"]
    ],
    "display": [
        ["vibrant", "positive"],
        ["crisp", "positive"],
        ["bright", "positive"],
        ["sharp", "positive"],
        ["colorful", "positive"],
        ["high-resolution", "positive"],
        ["stunning", "positive"],
        ["clear", "positive"],
        ["detailed", "positive"],
        ["wide viewing angles", "positive"],
        ["gorgeous", "positive"],
        ["lifelike", "positive"],
        ["immersive", "positive"],
        ["dim", "negative"],
        ["blurry", "negative"],
        ["washed out", "negative"],
        ["poor viewing angles", "negative"],
        ["flickering", "negative"],
        ["grainy", "negative"],
        ["low-resolution", "negative"],
        ["dull", "negative"],
        ["narrow viewing angles", "negative"],
        ["ghosting", "negative"],
        ["pixelated", "negative"],
        ["glare-prone", "negative"],
        ["unresponsive", "negative"],
        ["adequate", "neutral"],
        ["sufficient", "neutral"],
        ["acceptable", "neutral"],
        ["fair", "neutral"],
        ["mediocre", "neutral"],
        ["average", "neutral"],
        ["standard", "neutral"],
        ["basic", "neutral"]
    ],
    "battery life": [
        ["long-lasting", "positive"],
        ["short-lived", "negative"],
        ["durable", "positive"],
        ["poor", "negative"],
        ["impressive", "positive"],
        ["disappointing", "negative"],
        ["excellent", "positive"],
        ["weak", "negative"],
        ["unreliable", "negative"],
        ["great", "positive"],
        ["mediocre", "neutral"],
        ["sufficient", "neutral"],
        ["adequate", "neutral"],
        ["inadequate", "negative"],
        ["decent", "neutral"],
        ["remarkable", "positive"],
        ["subpar", "negative"],
        ["superb", "positive"],
        ["inferior", "negative"],
        ["optimal", "positive"],
        ["unsatisfactory", "negative"],
        ["longevity", "positive"],
        ["drains quickly", "negative"],
        ["sustainable", "positive"],
        ["average", "neutral"]
    ],
    "portability": [
        ["lightweight", "positive"],
        ["compact", "positive"],
        ["easy to carry", "positive"],
        ["portable", "positive"],
        ["travel-friendly", "positive"],
        ["ultra-portable", "positive"],
        ["heavy", "negative"],
        ["bulky", "negative"],
        ["cumbersome", "negative"],
        ["unwieldy", "negative"],
        ["hard to carry", "negative"],
        ["too big", "negative"],
        ["weights a ton", "negative"],
        ["not travel-friendly", "negative"],
        ["heft", "negative"],
        ["average size", "neutral"],
        ["standard size", "neutral"],
        ["typical weight", "neutral"],
        ["manageable", "neutral"],
        ["not too heavy", "neutral"]
    ],
    "price": [
        ["affordable", "positive"],
        ["cheap", "positive"],
        ["cost-effective", "positive"],
        ["economical", "positive"],
        ["budget-friendly", "positive"],
        ["value for money", "positive"],
        ["worth every penny", "positive"],
        ["inexpensive", "positive"],
        ["priced well", "positive"],
        ["reasonable", "positive"],
        ["overpriced", "negative"],
        ["expensive", "negative"],
        ["costly", "negative"],
        ["high-priced", "negative"],
        ["pricey", "negative"],
        ["rip-off", "negative"],
        ["not worth the money", "negative"],
        ["a fortune", "negative"],
        ["exorbitant", "negative"],
        ["steep", "negative"],
        ["moderately priced", "neutral"],
        ["average priced", "neutral"],
        ["mid-range", "neutral"],
        ["fairly priced", "neutral"],
        ["standard price", "neutral"]
    ],
    "build quality": [
        ["sturdy", "positive"],
        ["well-built", "positive"],
        ["solid construction", "positive"],
        ["durable", "positive"],
        ["high-quality build", "positive"],
        ["robust", "positive"],
        ["premium feel", "positive"],
        ["sleek design", "positive"],
        ["lightweight", "positive"],
        ["elegant", "positive"],
        ["fragile", "negative"],
        ["flimsy", "negative"],
        ["cheaply made", "negative"],
        ["poorly constructed", "negative"],
        ["breaks easily", "negative"],
        ["plasticky", "negative"],
        ["bulkier design", "negative"],
        ["heats up", "negative"],
        ["prone to scratches", "negative"],
        ["bends easily", "negative"],
        ["average build", "neutral"],
        ["standard build quality", "neutral"],
        ["moderate durability", "neutral"],
        ["acceptable construction", "neutral"],
        ["unremarkable design", "neutral"],
    ],
    "connectivity": [
        ["fast Wi-Fi connection", "positive"],
        ["instant pairing", "positive"],
        ["seamless connectivity", "positive"],
        ["robust Bluetooth connection", "positive"],
        ["universal compatibility", "positive"],
        ["abundant ports", "positive"],
        ["lightning-fast data transfer", "positive"],
        ["efficient syncing", "positive"],
        ["plug and play", "positive"],
        ["wide range of ports", "positive"],
        ["unstable Wi-Fi", "negative"],
        ["spotty connection", "negative"],
        ["limited Bluetooth range", "negative"],
        ["insufficient ports", "negative"],
        ["slow data transfer", "negative"],
        ["frequent disconnections", "negative"],
        ["incompatible with certain devices", "negative"],
        ["laggy internet connection", "negative"],
        ["troublesome pairing", "negative"],
        ["restricted connectivity options", "negative"],
        ["adequate ports", "neutral"],
        ["standard Bluetooth connectivity", "neutral"],
        ["average Wi-Fi speed", "neutral"],
        ["basic connectivity features", "neutral"],
        ["minimal lag", "neutral"]
    ],
    "software":  [
        ["user-friendly", "positive"],
        ["intuitive", "positive"],
        ["feature-rich", "positive"],
        ["reliable", "positive"],
        ["efficient", "positive"],
        ["versatile", "positive"],
        ["buggy", "negative"],
        ["slow", "negative"],
        ["clunky", "negative"],
        ["outdated", "negative"],
        ["complicated", "negative"],
        ["resource-heavy", "negative"],
        ["crashes often", "negative"],
        ["limited functionality", "negative"],
        ["incompatible", "negative"],
        ["adequate", "neutral"],
        ["basic", "neutral"],
        ["standard", "neutral"],
        ["functional", "neutral"],
        ["sufficient", "neutral"]
    ],
    "warranty and support": [
        ["reliable warranty", "positive"],
        ["helpful support", "positive"],
        ["efficient customer service", "positive"],
        ["prompt technical support", "positive"],
        ["comprehensive coverage", "positive"],
        ["extended warranty option", "positive"],
        ["peace of mind", "positive"],
        ["user-friendly support", "positive"],
        ["quick response time", "positive"],
        ["professional assistance", "positive"],
        ["limited warranty", "negative"],
        ["unhelpful support", "negative"],
        ["poor customer service", "negative"],
        ["slow response", "negative"],
        ["tedious warranty claim process", "error on my side"],  # Intended to write "negative"
        ["lacking coverage", "negative"],
        ["no warranty", "negative"],
        ["ineffective technical support", "negative"],
        ["complicated support system", "negative"],
        ["frustrating experience", "negative"],
        ["standard warranty", "neutral"],
        ["adequate support", "neutral"],
        ["average customer service", "neutral"],
        ["basic coverage", "neutral"],
        ["normal response time", "neutral"]
    ]
}